### ISSUE TITLE
Installation issue: can't copy 'doc/zas-agent.0.1.1.pdf'

### ISSUE THREAD

**Issue by alexanderzobnin** [vulogov/zas_agent#1]
Hi, Vladimir! Thanks for this great tool! I get error while installing zas_agent: 
`error: can't copy 'doc/zas-agent.0.1.1.pdf': doesn't exist or not a regular file`
It's due in setup.py:

```
data_files=[
        ("/etc/zas", ['etc/network.scenario'],),
        ("/etc", ["etc/zas_scenario.cfg"]),
        ("/usr/share/zas_agent", ["doc/zas-agent.0.1.1.pdf",]),
...
```

, but real file name is `doc/zas-agent-0.1.1.pdf`.

**Comment by vulogov** [comment]
Thanks.

Corrected.

V.

Jan 3, 2016, в 10:49, Alexander Zobnin notifications@github.com написал(а):
