### ISSUE TITLE
Multiple ZAS Agent instances

### ISSUE THREAD

**Issue by alexanderzobnin** [vulogov/zas_agent#4]
When I started several zas agent instances on one host with scenarios it uses the same redis instance, right? And data generated by agents are very similar (because it use the same data from redis). Can I use different redis stores for each agent?

**Comment by vulogov** [comment]
At this version, you _must_ use different REDIS store for an each instance. Later on, I will implement  the mechanism, which will allow you to use the same instance.

**Comment by alexanderzobnin** [comment]
Ok, thanks!
